// OPTIONAL — run this ONCE, locally, to (re)generate data/ai.json with your own Gemini key.
// The live website never runs this and never needs a key. Nothing here is deployed.
//
// Usage (Node 18+):
//   1. Get a free key at https://aistudio.google.com  ->  "Get API key"
//   2. In a terminal in the project folder:
//        GEMINI_API_KEY=your_key_here node scripts/generate-ai.mjs
//      (Windows PowerShell:  $env:GEMINI_API_KEY="your_key_here"; node scripts/generate-ai.mjs)
//
// It only ever sends the SYNTHETIC, already-masked report facts to Gemini — mirroring
// Mosaic's "only redacted info leaves the device" design.

import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = join(__dirname, "..");
const MODEL = "gemini-2.0-flash";
const KEY = process.env.GEMINI_API_KEY;

if (!KEY) {
  console.error("Missing GEMINI_API_KEY. See instructions at the top of this file.");
  process.exit(1);
}

const reports = JSON.parse(readFileSync(join(root, "data", "reports.json"), "utf8")).reports;

function factsFor(r) {
  // Send only bounded, masked facts — never anything that identifies a real person.
  const base = r.baseline, cur = r.current;
  return `Person: ${r.name} (synthetic). SSN masked ${r.maskedSsn}.
Baseline (${base.date}) score ${base.score}; Current (${cur.date}) score ${cur.score}.
Baseline accounts: ${JSON.stringify(base.accounts)}
Current accounts: ${JSON.stringify(cur.accounts)}
Baseline inquiries: ${JSON.stringify(base.inquiries)}
Current inquiries: ${JSON.stringify(cur.inquiries)}`;
}

const prompt = (r) => `You are a credit-report fraud-recovery assistant. Using ONLY the facts below,
return a JSON object with exactly these keys:
  "riskLevel": one of "High" | "Medium" | "Low"
  "summary": 2-4 sentences, plain English, describing what changed and whether it looks like fraud
  "recommendedActions": array of 3-4 short action strings
  "letter": a ready-to-edit dispute or validation letter as plain text (use \\n for line breaks)
Do not include markdown fences. Facts:
${factsFor(r)}`;

async function callGemini(text) {
  const url = `https://generativelanguage.googleapis.com/v1beta/models/${MODEL}:generateContent?key=${KEY}`;
  const res = await fetch(url, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({
      contents: [{ parts: [{ text }] }],
      generationConfig: { temperature: 0.4, maxOutputTokens: 900, responseMimeType: "application/json" },
    }),
  });
  if (!res.ok) throw new Error(`Gemini ${res.status}: ${await res.text()}`);
  const data = await res.json();
  return JSON.parse(data.candidates[0].content.parts[0].text);
}

const content = {};
for (const r of reports) {
  process.stdout.write(`Generating ${r.id}... `);
  content[r.id] = await callGemini(prompt(r));
  console.log("done");
}

const out = {
  _note: "Pre-generated AI content. Regenerated by scripts/generate-ai.mjs.",
  generatedBy: MODEL,
  content,
};
writeFileSync(join(root, "data", "ai.json"), JSON.stringify(out, null, 2));
console.log("Wrote data/ai.json");
